parameters:
#    pkonekt_index.example.class: Pkonekt\IndexBundle\Example

services:
#    pkonekt_index.example:
#        class: %pkonekt_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
