parameters:
#    pkonekt_user.example.class: Pkonekt\UserBundle\Example

services:
#    pkonekt_user.example:
#        class: %pkonekt_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
